/*
 * Copyright © 2026 Chiloven945
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    `java-library`
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.lombok)
}

dependencies {
    api(libs.jackson.core)
    api(libs.jackson.core.databind)
    api(libs.jackson.module.kotlin)

    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.zip4j)

    compileOnly(libs.lombok)
    annotationProcessor(libs.lombok)
}

@Suppress("UNCHECKED_CAST")
val lukosDisplayVersionProvider =
    rootProject.extra["lukosDisplayVersionProvider"] as Provider<String>

val generatedBuildInfoDir =
    layout.buildDirectory.dir("generated/sources/buildInfo/kotlin")

fun String.toKotlinStringLiteral(): String = buildString {
    append('"')

    for (ch in this@toKotlinStringLiteral) {
        when (ch) {
            '\\' -> append("\\\\")
            '"' -> append("\\\"")
            '$' -> {
                append('\\')
                append('$')
            }

            '\n' -> append("\\n")
            '\r' -> append("\\r")
            '\t' -> append("\\t")
            else -> append(ch)
        }
    }

    append('"')
}

val generateBuildInfo by tasks.registering {
    val outputFileProvider = generatedBuildInfoDir.map {
        it.file("top/chiloven/lukosbot2/BuildInfo.kt")
    }

    inputs.property("displayVersion", lukosDisplayVersionProvider)
    outputs.file(outputFileProvider)

    doLast {
        val outputFile = outputFileProvider.get().asFile
        outputFile.parentFile.mkdirs()

        val displayVersion = lukosDisplayVersionProvider.get()

        outputFile.writeText(
            """
            package top.chiloven.lukosbot2

            /**
             * Generated by Gradle. Do not edit manually.
             */
            object BuildInfo {
                const val VERSION: String = ${displayVersion.toKotlinStringLiteral()}
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin {
    sourceSets.named("main") {
        kotlin.srcDir(generatedBuildInfoDir)
    }
}

tasks.withType<KotlinCompile>().configureEach {
    dependsOn(generateBuildInfo)
}
